### ISSUE TITLE
如何判断除夕？

### ISSUE THREAD

**Issue by IAIAE** [waterbeside/lunisolar#1]
除夕是大月30，小月29，用这个库怎么判断？

**Comment by waterbeside** [comment]
> 除夕是大月30，小月29，用这个库怎么判断？

Hi IAIAE:
**除夕**为阴历新年的前一天，本库中可通过`Lunar`对象的`lunarNewYearDay`属性取得该农历年春节，然后再前减一天，便是除夕。
而本库1.0.0版本开始，`Lunar`对象加入了`lastDayOfYear`属性，可直接取得该阴历年的最后一天(返回Date对象)。

示例:
```typescript
const ldoy: Date = lunisolar('2022-10-22').lunar.lastDayOfYear
// ldoy为 日期'2023-01-21'的Date对象
```

如果单线想判定是大月还是小月，可通过`lunar`的`isBigMonth`属性取得当前月是否大月
