### ISSUE TITLE
24节气返回的是繁体字

### ISSUE THREAD

**Issue by stalkercn** [waterbeside/lunisolar#13]
问题：24节气返回的是繁体字
预期：返回简体字

影响版本号：v2.2.2

操作系统环境：Win10 21H1
开发环境： Vue3 + TS

**Comment by waterbeside** [comment]
您好，lunisolar默认显示语言为繁体中文，如果想显示简体中文，请参考`文档-国际化`这一章节。导入并加载简体中文语言包即可。
https://lunisolar.js.org/guide/i18n.html

十分感谢你的支持！
