### ISSUE TITLE
24节气错误 部分重复，部分丢失

### ISSUE THREAD

**Issue by mobei95** [waterbeside/lunisolar#14]
通过接口获取到的24节气，数量是没错的，但是部分节气重复出现了，以23年为例，大雪，立夏都重复了，而立春则没有出现

**Comment by mobei95** [comment]
![image](https://github.com/waterbeside/lunisolar/assets/26057989/8dc3c297-5721-422d-964b-9afe31d176e1)

**Comment by waterbeside** [comment]
> ![image](https://github.com/waterbeside/lunisolar/assets/26057989/8dc3c297-5721-422d-964b-9afe31d176e1)
> 

感谢您的反馈，我会尽快检查和修复

**Comment by waterbeside** [comment]
> 通过接口获取到的24节气，数量是没错的，但是部分节气重复出现了，以23年为例，大雪，立夏都重复了，而立春则没有出现

您好，请问你是通过哪个接口查询的？方便贴一下代码？


以下是通过我的方式查询得到的：

```typescript
const names = lunisolar.SolarTerm.getNames()
for (let i = 0; i < 24; i++) {
  const dd = lunisolar.SolarTerm.findDate(2013, i)
  const name = names[i]
  console.log(i, name, dd)
}

// result: 
/**
0 小寒 [ 2013, 1, 5 ]
1 大寒 [ 2013, 1, 20 ]
2 立春 [ 2013, 2, 4 ]
3 雨水 [ 2013, 2, 18 ]
4 驚蟄 [ 2013, 3, 5 ]
5 春分 [ 2013, 3, 20 ]
6 清明 [ 2013, 4, 4 ]
7 穀雨 [ 2013, 4, 20 ]
8 立夏 [ 2013, 5, 5 ]
9 小滿 [ 2013, 5, 21 ]
10 芒種 [ 2013, 6, 5 ]
11 夏至 [ 2013, 6, 21 ]
12 小暑 [ 2013, 7, 7 ]
13 大暑 [ 2013, 7, 22 ]
14 立秋 [ 2013, 8, 7 ]
15 處暑 [ 2013, 8, 23 ]
16 白露 [ 2013, 9, 7 ]
17 秋分 [ 2013, 9, 23 ]
18 寒露 [ 2013, 10, 8 ]
19 霜降 [ 2013, 10, 23 ]
20 立冬 [ 2013, 11, 7 ]
21 小雪 [ 2013, 11, 22 ]
22 大雪 [ 2013, 12, 7 ]
23 冬至 [ 2013, 12, 22 ]
*/
```

**Comment by waterbeside** [comment]
> 通过接口获取到的24节气，数量是没错的，但是部分节气重复出现了，以23年为例，大雪，立夏都重复了，而立春则没有出现

您好，请问你是通过哪个接口查询的？方便贴一下代码？


以下是通过我的方式查询得到的：

```typescript
const names = lunisolar.SolarTerm.getNames()
for (let i = 0; i < 24; i++) {
  const dd = lunisolar.SolarTerm.findDate(2013, i)
  const name = names[i]
  console.log(i, name, dd)
}

// result: 
/**
0 小寒 [ 2013, 1, 5 ]
1 大寒 [ 2013, 1, 20 ]
2 立春 [ 2013, 2, 4 ]
3 雨水 [ 2013, 2, 18 ]
4 驚蟄 [ 2013, 3, 5 ]
5 春分 [ 2013, 3, 20 ]
6 清明 [ 2013, 4, 4 ]
7 穀雨 [ 2013, 4, 20 ]
8 立夏 [ 2013, 5, 5 ]
9 小滿 [ 2013, 5, 21 ]
10 芒種 [ 2013, 6, 5 ]
11 夏至 [ 2013, 6, 21 ]
12 小暑 [ 2013, 7, 7 ]
13 大暑 [ 2013, 7, 22 ]
14 立秋 [ 2013, 8, 7 ]
15 處暑 [ 2013, 8, 23 ]
16 白露 [ 2013, 9, 7 ]
17 秋分 [ 2013, 9, 23 ]
18 寒露 [ 2013, 10, 8 ]
19 霜降 [ 2013, 10, 23 ]
20 立冬 [ 2013, 11, 7 ]
21 小雪 [ 2013, 11, 22 ]
22 大雪 [ 2013, 12, 7 ]
23 冬至 [ 2013, 12, 22 ]
*/
```

**Comment by mobei95** [comment]
我在文档中找到了这个接口，使用这个接口进行查询的；我已经改用了lunarJS来实现我的业务，没有当时的原始代码了
<img width="1329" alt="image" src="https://github.com/waterbeside/lunisolar/assets/26057989/79f744f1-4483-448b-98d9-41376f3bdf2c">

**Comment by waterbeside** [comment]
> 我在文档中找到了这个接口，使用这个接口进行查询的；我已经改用了lunarJS来实现我的业务，没有当时的原始代码了
> <img width="1329" alt="image" src="https://github.com/waterbeside/lunisolar/assets/26057989/79f744f1-4483-448b-98d9-41376f3bdf2c">
> 

十分抱歉，文档可能没写清楚，这个接口返回的日期列表，是从每年的第一个节气(小寒)开始按顺序列出的，因为固定每个公历月有两个节气，所以`月份`可自行推断，故列表只给出了`日`。

感谢你的提出。

**Comment by mobei95** [comment]
也就是说需要自己按照顺序去补充月份对吗；比如文档示例里的前两项[5, 20]需要自主补上1月，紧接着的[4, 19]需要自主补上2月才能得到正确的节气时间；

抱歉，我一直以为返回的这个数组是节气的编号

**Comment by waterbeside** [comment]
该问题没异议就关闭了。
