### ISSUE TITLE
是不是没有年份的属相？比如猪年、虎年

### ISSUE THREAD

**Issue by diamont1001** [waterbeside/lunisolar#17]

**Comment by waterbeside** [comment]
> 

你好，如果想取生肖，可以参考 format方法的使用。

```
lunisolar('2022/03/10').format('cZ年') // '虎年'
```

除了format外，暂时未设有其它方法。另外生肖是跟随年地支的。日后会考虑在地支类上添加生肖属性。

谢谢。

**Comment by diamont1001** [comment]
> > 
> 
> 你好，如果想取生肖，可以参考 **format** 方法的使用。
> 
> ```
> lunisolar('2022/03/10').format('cZ年') // '虎年'
> ```
> 
> `cZ` 为 `chinese zodiac` 缩写
> 
> 除了format外，暂时未设有其它方法。另外生肖是跟随年地支的, 日后会考虑在地支类上添加生肖属性。
> 
> 谢谢。

噢，感谢，`.format('cZ年')` 这个可以满足我的需求了，谢谢！
