### ISSUE TITLE
神煞计算的时候有重复，应该是规则不对，八字计算应该有流派设置的问题比如早子时晚子时

### ISSUE THREAD

**Issue by 52myu** [waterbeside/lunisolar#18]
如：以年支午计算神煞，则年支下边不应该有当前年支对应年支的神煞。

**Comment by waterbeside** [comment]
> 

十分感谢您提出的建议，
能否举个例子，方便我快速定位和测试改进。
谢谢。

**Comment by 52myu** [comment]
![12](https://github.com/waterbeside/lunisolar/assets/11611897/44cf53d7-a398-4f5b-b337-8d5b59ee8c5e)
年柱的神煞不应该再出现：将星 灾煞  
【（年支）午】遇【（非年支）午】才是将星，目前的计算逻辑明显把年支也计算了一次。
建议：神煞类别的组件不依赖于lunisolar，只需输入八字、大运、流年、流月...,除非lunisolar已经包含了所有类别的排盘规则。

**Comment by 52myu** [comment]
> > 
> 
> 十分感谢您提出的建议， 能否举个例子，方便我快速定位和测试改进。 谢谢。

以年支、日支计算的都应该会存在同样的问题

**Comment by waterbeside** [comment]
> ![12](https://github.com/waterbeside/lunisolar/assets/11611897/44cf53d7-a398-4f5b-b337-8d5b59ee8c5e)
> 年柱的神煞不应该再出现：将星 灾煞  
> 【（年支）午】遇【（非年支）午】才是将星，目前的计算逻辑明显把年支也计算了一次。
> 建议：神煞类别的组件不依赖于lunisolar，只需输入八字、大运、流年、流月...,除非lunisolar已经包含了所有类别的排盘规则。

十分感谢，我再看看。

**Comment by waterbeside** [comment]
> > > 
> > 
> > 
> > 十分感谢您提出的建议， 能否举个例子，方便我快速定位和测试改进。 谢谢。
> 
> 以年支、日支计算的都应该会存在同样的问题

关于‘年日支遇支’起例的问题已经修复了，可把 `@lunisolar/char8ex` 插件更新到`0.2.4`版本试试。

后续版本会再考虚把神煞类别的查询作为一个函数暴露出来而不用依赖lunisolar。以及早晚子时的设置也会在日后考虑。

**Comment by 52myu** [comment]
> > > > 
> > > 
> > > 
> > > 十分感谢您提出的建议， 能否举个例子，方便我快速定位和测试改进。 谢谢。
> > 
> > 
> > 以年支、日支计算的都应该会存在同样的问题
> 
> 关于‘年日支遇支’起例的问题已经修复了，可把 `@lunisolar/char8ex` 插件更新到`0.2.4`版本试试。
> 
> 后续版本会再考虚把神煞类别的查询作为一个函数暴露出来而不用依赖lunisolar。以及早晚子时的设置也会在日后考虑。

@lunisolar/char8ex 安装报错，目前使用的lunisolar版本为2.2.2
 npm install @lunisolar/plubin-char8ex @lunisolar/plugin-takesound
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@lunisolar%2fplubin-char8ex - Not found

**Comment by waterbeside** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 十分感谢您提出的建议， 能否举个例子，方便我快速定位和测试改进。 谢谢。
> > > 
> > > 
> > > 以年支、日支计算的都应该会存在同样的问题
> > 
> > 
> > 关于‘年日支遇支’起例的问题已经修复了，可把 `@lunisolar/char8ex` 插件更新到`0.2.4`版本试试。
> > 后续版本会再考虚把神煞类别的查询作为一个函数暴露出来而不用依赖lunisolar。以及早晚子时的设置也会在日后考虑。
> 
> @lunisolar/char8ex 安装报错，目前使用的lunisolar版本为2.2.2 npm install @lunisolar/plubin-char8ex @lunisolar/plugin-takesound npm ERR! code E404 npm ERR! 404 Not Found - GET https://registry.npmjs.org/@lunisolar%2fplubin-char8ex - Not found

十分抱歉，应该是我文档把 plugin 打错成 plubin 了 

 `npm install @lunisolar/plugin-char8ex @lunisolar/plugin-takesound`

再试试

**Comment by 52myu** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 十分感谢您提出的建议， 能否举个例子，方便我快速定位和测试改进。 谢谢。
> > > > 
> > > > 
> > > > 以年支、日支计算的都应该会存在同样的问题
> > > 
> > > 
> > > 关于‘年日支遇支’起例的问题已经修复了，可把 `@lunisolar/char8ex` 插件更新到`0.2.4`版本试试。
> > > 后续版本会再考虚把神煞类别的查询作为一个函数暴露出来而不用依赖lunisolar。以及早晚子时的设置也会在日后考虑。
> > 
> > 
> > @lunisolar/char8ex 安装报错，目前使用的lunisolar版本为2.2.2 npm install @lunisolar/plubin-char8ex @lunisolar/plugin-takesound npm ERR! code E404 npm ERR! 404 Not Found - GET https://registry.npmjs.org/@lunisolar%2fplubin-char8ex - Not found
> 
> 十分抱歉，应该是我文档把 plugin 打错成 plubin 了 （现己改正文档）
> 
> `npm install @lunisolar/plugin-char8ex @lunisolar/plugin-takesound`
> 
> 再试试。

可以了多谢大佬，大佬有没有交流群

**Comment by waterbeside** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 十分感谢您提出的建议， 能否举个例子，方便我快速定位和测试改进。 谢谢。
> > > > > 
> > > > > 
> > > > > 以年支、日支计算的都应该会存在同样的问题
> > > > 
> > > > 
> > > > 关于‘年日支遇支’起例的问题已经修复了，可把 `@lunisolar/char8ex` 插件更新到`0.2.4`版本试试。
> > > > 后续版本会再考虚把神煞类别的查询作为一个函数暴露出来而不用依赖lunisolar。以及早晚子时的设置也会在日后考虑。
> > > 
> > > 
> > > @lunisolar/char8ex 安装报错，目前使用的lunisolar版本为2.2.2 npm install @lunisolar/plubin-char8ex @lunisolar/plugin-takesound npm ERR! code E404 npm ERR! 404 Not Found - GET https://registry.npmjs.org/@lunisolar%2fplubin-char8ex - Not found
> > 
> > 十分抱歉，应该是我文档把 plugin 打错成 plubin 了 （现己改正文档）
> > 
> > `npm install @lunisolar/plugin-char8ex @lunisolar/plugin-takesound`
> > 
> > 再试试。
> 
> 可以了多谢大佬，大佬有没有交流群

项目人气不算很高，所以也没考虑到设交流群。
