### ISSUE TITLE
是否支持时干支

### ISSUE THREAD

**Issue by qcyblm** [waterbeside/lunisolar#19]
![image](https://github.com/waterbeside/lunisolar/assets/64412486/bcb7977b-d6b0-47af-9f10-71abf249d24b)

**Comment by waterbeside** [comment]
> ![image](https://github.com/waterbeside/lunisolar/assets/64412486/bcb7977b-d6b0-47af-9f10-71abf249d24b)
> 

关于时干支可参考文档 八字-时柱：

https://lunisolar.js.org/guide/functional/char8.html#%E6%97%B6%E6%9F%B1

可取得当前实例的时干支
