### ISSUE TITLE
目前发现4个日期没法获取月柱的天干地支

### ISSUE THREAD

**Issue by shx1368** [waterbeside/lunisolar#2]
分别是
2018-12-6
2018-12-5
2018-12-4
2018-12-3

lunisolar('2018-12-6').format('cY cM cD')
戊戌 undefinedundefined 壬申

**Comment by waterbeside** [comment]
> 分别是 2018-12-6 2018-12-5 2018-12-4 2018-12-3
> 
> lunisolar('2018-12-6').format('cY cM cD') 戊戌 undefinedundefined 壬申

Hi, shx1368:
十分感谢您的反馈，问题现已修复，请使用1.3.1及之后的版本。
谢谢
