### ISSUE TITLE
插件文档文本错误

### ISSUE THREAD

**Issue by Chanzhaoyu** [waterbeside/lunisolar#23]
GitHub 仓库内的 doc 是对的，但是文档网站是错误的，如下图：

<img width="853" alt="image" src="https://github.com/waterbeside/lunisolar/assets/24789441/8525a924-1462-4a92-afe3-d69d1ecf3cc6">

**Comment by waterbeside** [comment]
> GitHub 仓库内的 doc 是对的，但是文档网站是错误的，如下图：
> 
> <img alt="image" width="853" src="https://private-user-images.githubusercontent.com/24789441/301353410-8525a924-1462-4a92-afe3-d69d1ecf3cc6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NTQxOTMsIm5iZiI6MTcwNjc1Mzg5MywicGF0aCI6Ii8yNDc4OTQ0MS8zMDEzNTM0MTAtODUyNWE5MjQtMTQ2Mi00YTkyLWFmZTMtZDY5ZDFlY2YzY2M2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAyMTgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZjBlNDBkZDU2MmQ2OTg2NzU5MDRmMDM5MGIyZmJiNDg1MDM0NzZkNTIwODhkNTU1YzkwNDNjYzA2MDBiYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dW6lJ3QlquPt_CuoIkGvOig0H42cBsQrG0H7OqtnbmA">

十分感谢您提出的问题，文档现已更正，谢谢。
