### ISSUE TITLE
获取阴历日undefined

### ISSUE THREAD

**Issue by at86** [waterbeside/lunisolar#3]
const dt = new Date("2022/11/23 18:10:23");
  const d = lunisolar(dt);
  console.log(
    "---------",
    d.lunar.getDayName(),
    d.lunar.day
  );

--------- undefined 0

**Comment by waterbeside** [comment]
hi at86:
十分感谢您的反馈，现在已经修复该问题，请使用最近更新的v1.4.1版本

**Comment by mokai** [comment]
2023-3-21这天getDayName也为undefined了，业务层手动兼容了下

```
const lunar = lunisolar(props.date.toDate()).lunar;
let dayName = lunar.getDayName();
if (!dayName && lunisolar(props.date.add(-1, 'day').toDate()).lunar.day === 29) {
  dayName = '三十';
}
```
