### ISSUE TITLE
1986年到1991年间 阴历转阳历时辰出错

### ISSUE THREAD

**Issue by marga8080** [waterbeside/lunisolar#31]
1986年到1991年间 这六年 阴历转阳历时辰出错
比如农历1986年6月11日午时
```
let ymd = {
                year: 1986,
                month: 6,
                day: 11,
                hour: '午'
            }
            // console.log(ymd)
            const ob = lunisolar.fromLunar(ymd)
            console.log(ob.format('YYYY-MM-DD HH:mm'))
```
正确应该是1986-07-17 12:00
但是得到的却是1986-07-17 13:00

**Comment by waterbeside** [comment]
> 1986年到1991年间 这六年 阴历转阳历时辰出错 比如农历1986年6月11日午时
> 
> ```
> let ymd = {
>                 year: 1986,
>                 month: 6,
>                 day: 11,
>                 hour: '午'
>             }
>             // console.log(ymd)
>             const ob = lunisolar.fromLunar(ymd)
>             console.log(ob.format('YYYY-MM-DD HH:mm'))
> ```
> 
> 正确应该是1986-07-17 12:00 但是得到的却是1986-07-17 13:00

您好，我用了你的示例去测式，返回的是 `1986-07-17 12:00` 并没有复现你所说的问题。

我也再检查了一下代码，理论上时辰不会返回单数点给你，

fromLunar的转换逻辑是：
1，先把当年所有的阴历新年对应的公历日期查出来，转为date对象，使用 xxxx-xx-xx 日期字符串转换，得到的是当地0时的日期 `nyd` 。
2，计算目标阴历日期 与  `nyd` 相差多少天 `diffDay` ,
3,  计算时辰，取得`午`时的时辰顺序索引  `6`，
4， `nyd时间戳 + (diffDay * 24 * 60 * 60 * 1000) + (6 * 2 * 60 * 60 * 1000)`  所得到的新时间戳就是结果。 因为nyd取的是0点时间，而时辰索引必定 * 2，所以计算出来的结果的时间必定是双数钟点时间。

初步怀疑原因：
1 浏览器是否装有时区相关的插件，影响显示？

**Comment by marga8080** [comment]
![image](https://github.com/user-attachments/assets/9be3f474-f173-4fb8-989b-9d7a68a23439)
![image](https://github.com/user-attachments/assets/d2de3637-e411-406c-a956-7764ca49c342)
![image](https://github.com/user-attachments/assets/a1f3e776-f236-4f18-8a00-b040d48261af)
lunisolar 版本为2.5.0

**Comment by marga8080** [comment]
我国在1986年到1991年这六年时间实行夏令时，导致那几天时钟拨快一小时
https://upimg.baike.so.com/doc/1958074-2072189.html

**Comment by marga8080** [comment]
在这期间晚上23点多阳历转阴历已经为次日，但是八字日主没变成次日

![Image](https://github.com/user-attachments/assets/e921ac55-a908-4962-85ab-9b8c13a217f7)

![Image](https://github.com/user-attachments/assets/2a8ef334-6ab6-46af-a7c6-377484f5bcc1)

这个两个时间的八字正确结果应该要一样的

```
            let ob = lunisolar('1986/07/17 00:30')
            console.log(ob.format('YYYY-MM-DD HH:mm'))
            console.log(ob.format('lY年 lM lD lH時'))
            console.log(ob.format('[八字]：cY cM cD cH') )

            ob = lunisolar('1986/07/16 23:30')
            console.log(ob.format('YYYY-MM-DD HH:mm'))
            console.log(ob.format('lY年 lM lD lH時'))
            console.log(ob.format('[八字]：cY cM cD cH') )
```
结果：
1986-07-17 00:30
一九八六年 六月 十一 子時
 八字：丙寅 乙未 壬戌 庚子
1986-07-16 23:30
 一九八六年 六月 十一 子時
八字：丙寅 乙未 辛酉 戊子

**Comment by waterbeside** [comment]
> 在这期间晚上23点多阳历转阴历已经为次日，但是八字日柱没变成次日
> 
> ![Image](https://github.com/user-attachments/assets/e921ac55-a908-4962-85ab-9b8c13a217f7)
> 
> ![Image](https://github.com/user-attachments/assets/2a8ef334-6ab6-46af-a7c6-377484f5bcc1)
> 
> ```
>             let ob = lunisolar('1986/07/17 00:30')
>             console.log(ob.format('YYYY-MM-DD HH:mm'))
>             console.log(ob.format('lY年 lM lD lH時'))
>             console.log(ob.format('[八字]：cY cM cD cH') )
> 
>             ob = lunisolar('1986/07/16 23:30')
>             console.log(ob.format('YYYY-MM-DD HH:mm'))
>             console.log(ob.format('lY年 lM lD lH時'))
>             console.log(ob.format('[八字]：cY cM cD cH') )
> ```
> 
> 输出： 1986-07-17 00:30 一九八六年 六月 十一 子時 八字：丙寅 乙未 壬戌 庚子 1986-07-16 23:30 一九八六年 六月 十一 子時 八字：丙寅 乙未 辛酉 戊子
> 
> 这个两个时间的八字正确结果应该要一样的，但是1986-07-16 23:30日柱和时柱不对

感谢发现问题，该问题修复了，请更新到v2.5.2版本试试。
