### ISSUE TITLE
2024年9月 应该是小月 

### ISSUE THREAD

**Issue by C16103112** [waterbeside/lunisolar#32]
const d = lunisolar('2024-9')
 console.log(d.lunar.isBigMonth)
 返回了true

**Comment by waterbeside** [comment]
> const d = lunisolar('2024-9') console.log(d.lunar.isBigMonth) 返回了true

你好，lunisolar('2024-9')  相当于 lunisolar('2024-09-01')。

2024-09-01当天是农历七月二九号。

d.lunar 是阴历实例， 在阴历月是七月， 该年的阴历七月有三十天，所以是大月。
