### ISSUE TITLE
中元节日期有争议

### ISSUE THREAD

**Issue by Miss-Sixty** [waterbeside/lunisolar#33]
感觉大部分地方都是农历7月15日中元节，看了百度上也是农历7月15日，但是这个库却是7月14日。

**Comment by waterbeside** [comment]
> 感觉大部分地方都是农历7月15日中元节，看了百度上也是农历7月15日，但是这个库却是7月14日。

查了一下，有些说华北地区是十五，华南是十四。 不过我也认为十五比较合理，毕竟上元下元都是十五。

我稍后调整。谢谢反馈

**Comment by waterbeside** [comment]
中元节调整为七月十五，已更新版本v2.5.1
