### ISSUE TITLE
术数之源离不开天干地支

### ISSUE THREAD

**Issue by rainTai** [waterbeside/lunisolar#6]
作者所做项目对我的术数线上化很有帮助~

**Comment by waterbeside** [comment]
> 作者所做项目对我的术数线上化很有帮助~

十分感谢您的支持。

如果使用中发现有任何问题，可以提交新的issue，亦欢迎贡献代码。

**Comment by rainTai** [comment]
应该是浏览器积累的卡顿，强刷之后正常
